Add main page
js-tasks-ru/htmlcss-20210409_kivals-90 pull request #2
Opened 2021-04-19 08:44 UTC by kivals

2021-04-19 08:44 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-04-19 09:27 UTC, GSemikozov requested changes

2021-04-19 09:27 UTC, GSemikozov commented on components/footer/footer.css
> +    margin-bottom: 32px;
один момент на который здесь стоит обратить внимание дополнительно - для тайтлов и некоторых других элементов используется другой шрифт нежели мы определили в fonts.css

2021-04-19 14:57 UTC, GSemikozov requested changes

2021-04-19 14:57 UTC, GSemikozov commented on assets/css/normalize.css
> +h1,h2,h3,h4,h5,h6{font-weight: inherit;font-size: inherit;}
кажется излишним правило - от чего будут наследоваться font-weight и font-size: inherit? По умолчанию, как мы помним, значения шрифтовых свойств и так наследуются от родителя.

2021-04-20 06:19 UTC, kivals commented on assets/css/normalize.css
> +h1,h2,h3,h4,h5,h6{font-weight: inherit;font-size: inherit;}
Да, действительно. Скопировал, неподумав.

2021-04-22 06:52 UTC, GSemikozov approved these changes

2021-04-22 06:52 UTC, merged