Lesson2. Task3. Main page cards
js-tasks-ru/htmlcss-20210409_kivals-90 pull request #7
Opened 2021-05-05 08:33 UTC by kivals

2021-05-05 08:33 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-05-06 09:46 UTC, GSemikozov requested changes

2021-05-06 09:46 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +    <div style='padding: 50px; width: 500px; height: 300px' class='wrapper'>
если не встраивать в этот контейнер, то график не отобразится - поэтому для histogram__body лучше задать минимальную высоту, например, по дизайну в 50px

2021-05-06 09:46 UTC, GSemikozov commented on components/histogram/histogram.css
> +.histogram {
этот компонент относится к задачнику, не стоит дублировать - на Главную можно подключать html/css прямо из папки компонента в задачнике

2021-05-07 08:11 UTC, closed without merging